#!/usr/bin/env bash
# installs nginx and configures it on a remote server
apt update
apt install nginx -y
ufw allow 22
ufw allow 80
ufw enable
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
