#!/usr/bin/env bash
# installs nginx and configures it on a remote server
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 301 Moved Permanently;' /etc/nginx/sites-available/default
service nginx start
