#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 301 Moved Permanently;' /etc/nginx/sites-available/default
sed -i 'listen 80 default_server; /a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
service nginx start
