#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-1.7 -y
apt-get update
apt-get install haproxy -y
echo "frontend web-front
        bind *:80
        default_backend web-backend
backend web-backend
        balance roundrobin
        server 40998-web-01 54.173.84.88:80 check
        server 40998-web-02 34.204.61.191:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
