#!/usr/bin/env bash
# Configures a new Ubuntu server with a HAproxy load-balancer
apt-get update
apt-get install software-properties-common -y
add-apt-repository ppa:vbernat/haproxy -y
apt-get update
apt-get install haproxy -y
echo "ENABLED=1" >> /etc/default/haproxy
sed -i '/504.http/a \\bind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 40998-web-01 52.91.178.209:80 check\n\tserver 40998-web-02 18.210.17.109:80 check' /etc/haproxy/haproxy.cfg
service haproxy start
