#!/usr/bin/env bash
# configuring ubuntu server localhost and facebook to 127.0.0.2 and 8.8.8.8 respectivly
cp /etc/hosts ~/hosts.n
sed -i 's/.*localhost/127.0.0.2 localhost/g' ~hosts.n
sed -i 's/.*facebook.com//g' ~hosts.n
sed -i 'a 8.8.8.8 facebook.com' ~hosts.n
cp -f ~/hosts.n /etc/hosts
