#!/usr/bin/env bash
# configuring ubuntu server localhost and facebook to 127.0.0.2 and 8.8.8.8 respectivly
cp /etc/hosts /etc/hosts.n
sudo -i 's/.*localhost/127.0.0.2 localhost/g' /etc/hosts.n
sudo -i 's/.*facebook.com//g' /etc/hosts.n
sudo -i 'a 8.8.8.8 facebook.com' /etc/hosts.n
cp -f /etc/hosts.n /etc/hosts
